In [41]:
import numpy as np
import torch

rangeBins = np.loadtxt('rangeBins.txt')
azimuthBins = np.loadtxt('azimuthBins.txt')

rangeBinsTensor = torch.from_numpy(rangeBins)
azimuthBinsTensor = torch.from_numpy(azimuthBins)

azimuthBins, rangeBins, azimuthBinsTensor.shape[0], rangeBinsTensor.shape

(array([-1.57079633e+00, -1.21537513e+00, -1.06543582e+00, -9.48427838e-01,
        -8.48062079e-01, -7.58040765e-01, -6.75131533e-01, -5.97406417e-01,
        -5.23598776e-01, -4.52816595e-01, -3.84396774e-01, -3.17823704e-01,
        -2.52680255e-01, -1.88616386e-01, -1.25327831e-01, -6.25407618e-02,
         1.13086389e-15,  6.25407618e-02,  1.25327831e-01,  1.88616386e-01,
         2.52680255e-01,  3.17823704e-01,  3.84396774e-01,  4.52816595e-01,
         5.23598776e-01,  5.97406417e-01,  6.75131533e-01,  7.58040765e-01,
         8.48062079e-01,  9.48427838e-01,  1.06543582e+00,  1.21537513e+00]),
 array([ 0.      ,  0.073125,  0.14625 ,  0.219375,  0.2925  ,  0.365625,
         0.43875 ,  0.511875,  0.585   ,  0.658125,  0.73125 ,  0.804375,
         0.8775  ,  0.950625,  1.02375 ,  1.096875,  1.17    ,  1.243125,
         1.31625 ,  1.389375,  1.4625  ,  1.535625,  1.60875 ,  1.681875,
         1.755   ,  1.828125,  1.90125 ,  1.974375,  2.0475  ,  2.120625,
         2.19375 ,  

In [40]:
polar_coords = torch.from_numpy(np.array([[
    [5, 2],
    [3, 4],
    [5, 6]
], [
    [9, 1],
    [6, 1],
    [3, 0]
]]))
B, N, _ = polar_coords.size()


azimuth_idxs = torch.index_select(polar_coords, 2, torch.tensor([0]))  # B x N x 1
range_idxs = torch.index_select(polar_coords, 2, torch.tensor([1]))  # B x N x 1

_azimuthBinsTensor = torch.reshape(azimuthBinsTensor, (1, 1, azimuthBinsTensor.shape[0]))
_rangeBinsTensor = torch.reshape(rangeBinsTensor, (1, 1, rangeBinsTensor.shape[0]))

_azimuthBinsTensor = _azimuthBinsTensor.expand(B, N, -1)
_rangeBinsTensor = _rangeBinsTensor.expand(B, N, -1)
azimuths = torch.gather(_azimuthBinsTensor, 2, azimuth_idxs)  # B x N x 1
ranges = torch.gather(_rangeBinsTensor, 2, range_idxs)  # B x N x 1

x = torch.mul(ranges, torch.cos(azimuths))
y = torch.mul(ranges, torch.sin(azimuths))

result = torch.cat((x, y), 2)


# _azimuthBinsTensor.shape, _rangeBinsTensor.shape, azimuth_idxs.shape, range_idxs.shape, azimuths.shape, ranges.shape
result.shape, x, y, result


(torch.Size([2, 3, 2]),
 tensor([[[0.1062],
          [0.1705],
          [0.3186]],
 
         [[0.0658],
          [0.0571],
          [0.0000]]], dtype=torch.float64),
 tensor([[[-0.1005],
          [-0.2377],
          [-0.3016]],
 
         [[-0.0320],
          [-0.0457],
          [-0.0000]]], dtype=torch.float64),
 tensor([[[ 0.1062, -0.1005],
          [ 0.1705, -0.2377],
          [ 0.3186, -0.3016]],
 
         [[ 0.0658, -0.0320],
          [ 0.0571, -0.0457],
          [ 0.0000, -0.0000]]], dtype=torch.float64))

In [20]:
a = torch.from_numpy(np.array([1, 2, 3]))
b = torch.from_numpy(np.array([2, 3, 4]))
c = torch.mul(a, b)

a,b,c, torch.cos(a)


(tensor([1, 2, 3]),
 tensor([2, 3, 4]),
 tensor([ 2,  6, 12]),
 tensor([ 0.5403, -0.4161, -0.9900]))